### ISSUE TITLE
Substances les plus vendues : valeurs axe erronées

### ISSUE THREAD

**Issue by dicorynia** [AFB-dataviz/dataviz_bnvd#1]
Bonjour

Sur http://dataviz.statistiques.developpement-durable.gouv.fr/produits_phytopharmaceutiques/
Ain / Toutes substances / Tendances des Ventes / Substances les plus vendues

quand on change le nombre de substances à représenter, l'échelle de l'axe Y (Tonnes de substances vendues) change mais ne conserve pas les valeurs des substances :

**Avec une substance : glyphosate à 59 en 2008**

![2020-01-21 09_22_23-dataviz statistiques developpement-durable gouv fr_produits_phytopharmaceutiques](https://user-images.githubusercontent.com/31208891/72787157-a7871a00-3c2f-11ea-90d9-f9b7b4c1a7dd.png)

**Avec deux substances : glyphosate correspond à environ 95 en 2008** sur le graphique alors que la valeur affichée au survol est toujours 59

![2020-01-21 09_34_07-dataviz statistiques developpement-durable gouv fr_produits_phytopharmaceutiques](https://user-images.githubusercontent.com/31208891/72787970-3b0d1a80-3c31-11ea-9da1-91649c2c094b.png)

Il semble que l'échelle n'est juste que pour la dernière substance ajoutée...

**Comment by AFB-dataviz** [comment]
Merci de votre retour. 

Les axes et valeurs affichées sont bien corrects. 

L'axe des Y représente les quantités cumulées sur l'ensemble des substances affichées (ce qui explique que les valeurs changent sur le graphique en fonction du nombre de substances sélectionné) alors que les valeurs affichées au survol du graphique sont bien celles des quantités par substance (elles ne changent donc pas en fonction du nombre de substances sélectionné).

**Comment by dicorynia** [comment]
Merci pour ce retour.
Je n'avais effectivement pas compris que c'était du cumul, ce qui est évident a posteriori :-). Désolé.
